include ../../build/def.mk

PROGBIN = sbox_test
INC_PATH += -I../
INC_PATH += -I../../include
INC_PATH += -I../include -I../../rbtree/include
LD_LIBS_PATH += -L../.libs -L../../rbtree/.libs
LD_LIBS += -lsbox -lrbtree

include ../../build/bin.mk
